# Generated by Django 5.0.7 on 2024-11-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_rename_user_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='user',
        ),
    ]
