# Generated by Django 5.0.7 on 2024-12-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='learned_lessons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
