# Generated by Django 5.0.7 on 2024-12-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(default=False, verbose_name='is_artist'),
            preserve_default=False,
        ),
    ]
