# Generated by Django 5.0.7 on 2024-10-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
