# Generated by Django 5.0.7 on 2024-12-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_is_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
