# Generated by Django 5.0.7 on 2024-12-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='artist',
        ),
    ]
